export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';

export const OPEN_CONTACT_DIALOG = 'OPEN_CONTACT_DIALOG';
export const CLOSE_CONTACT_DIALOG = 'CLOSE_CONTACT_DIALOG';

export const SAVE_CONTACT = 'SAVE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
